const Map<int, String> females = {
  0: 'assets/avt/female/0.png',
  1: 'assets/avt/female/1.png',
  2: 'assets/avt/female/2.png',
  3: 'assets/avt/female/3.png',
  4: 'assets/avt/female/4.png',
  5: 'assets/avt/female/5.png',
  6: 'assets/avt/female/6.png',
  7: 'assets/avt/female/7.png',
  8: 'assets/avt/female/8.png',
  9: 'assets/avt/female/9.png',
  10: 'assets/avt/female/10.png',
  11: 'assets/avt/female/11.png',
  12: 'assets/avt/female/12.png',
  13: 'assets/avt/female/13.png',
  14: 'assets/avt/female/14.png',
  15: 'assets/avt/female/15.png',
  16: 'assets/avt/female/16.png',
  17: 'assets/avt/female/17.png',
  18: 'assets/avt/female/18.png',
  19: 'assets/avt/female/19.png',
  20: 'assets/avt/female/20.png',
  21: 'assets/avt/female/21.png',
  22: 'assets/avt/female/22.png',
  23: 'assets/avt/female/23.png',
  24: 'assets/avt/female/24.png',
};

const Map<int, String> males = {
  0: 'assets/avt/male/0.png',
  1: 'assets/avt/male/1.png',
  2: 'assets/avt/male/2.png',
  3: 'assets/avt/male/3.png',
  4: 'assets/avt/male/4.png',
  5: 'assets/avt/male/5.png',
  6: 'assets/avt/male/6.png',
  7: 'assets/avt/male/7.png',
  8: 'assets/avt/male/8.png',
  9: 'assets/avt/male/9.png',
  10: 'assets/avt/male/10.png',
  11: 'assets/avt/male/11.png',
  12: 'assets/avt/male/12.png',
  13: 'assets/avt/male/13.png',
  14: 'assets/avt/male/14.png',
  15: 'assets/avt/male/15.png',
  16: 'assets/avt/male/16.png',
  17: 'assets/avt/male/17.png',
  18: 'assets/avt/male/18.png',
  19: 'assets/avt/male/19.png',
  20: 'assets/avt/male/20.png',
  21: 'assets/avt/male/21.png',
  22: 'assets/avt/male/22.png',
  23: 'assets/avt/male/23.png',
  24: 'assets/avt/male/24.png',
};
